baseURL = 'https://jantari.github.io/LSUClient-docs'
languageCode = 'en-us'
title = 'LSUClient Documentation'

theme = 'hugo-book'

[params]
  BookTheme = 'auto'

[markup]
  [markup.highlight]
    style = 'nord'

[menu]
[[menu.after]]
  name = "ğŸ”— GitHub"
  url = "https://github.com/jantari/LSUClient"
  weight = 10

[[menu.after]]
  name = "ğŸ”— Release Notes"
  url = "https://github.com/jantari/LSUClient/releases"
  weight = 20

[[menu.after]]
  name = "ğŸ”— PowerShell Gallery"
  url = "https://www.powershellgallery.com/packages/LSUClient/"
  weight = 30

[[menu.after]]
#  name = "ğŸŒ Hugo Book Theme"
  name = "ğŸ”— Hugo Book Theme"
  url = "https://github.com/alex-shpak/hugo-book"
  weight = 40
