baseURL = 'https://jantari.github.io/lsuclient-docs'
languageCode = 'en-us'
title = 'LSUClient Documentation'

[module]
[[module.imports]]
  path = 'github.com/alex-shpak/hugo-book'

theme = 'hugo-book'

[params]
  BookTheme = 'auto'

[menu]
[[menu.after]]
  name = "ğŸŒGitHub"
  url = "https://github.com/jantari/LSUClient"
  weight = 10

[[menu.after]]
  name = "ğŸŒ PowerShell Gallery"
  url = "https://www.powershellgallery.com/packages/LSUClient/"
  weight = 20

[[menu.after]]
  name = "ğŸŒ Hugo Book Theme"
  url = "https://github.com/alex-shpak/hugo-book"
  weight = 30
